name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image (env only)
        env:
          APP_NAME: ${{ secrets.APP_NAME }}
          APP_ENV: ${{ secrets.APP_ENV }}
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_DEBUG: ${{ secrets.APP_DEBUG }}
          APP_URL: ${{ secrets.APP_URL }}
          LOG_CHANNEL: ${{ secrets.LOG_CHANNEL }}
          LOG_DEPRECATIONS_CHANNEL: ${{ secrets.LOG_DEPRECATIONS_CHANNEL }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SESSION_DRIVER: ${{ secrets.SESSION_DRIVER }}
          SESSION_LIFETIME: ${{ secrets.SESSION_LIFETIME }}
          REDIS_CLIENT: ${{ secrets.REDIS_CLIENT }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          MAIL_MAILER: ${{ secrets.MAIL_MAILER }}
          MAIL_SCHEME: ${{ secrets.MAIL_SCHEME }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_FROM_ADDRESS: ${{ secrets.MAIL_FROM_ADDRESS }}
          MAIL_FROM_NAME: ${{ secrets.MAIL_FROM_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
          AWS_URL: ${{ secrets.AWS_URL }}
          AWS_USE_PATH_STYLE_ENDPOINT: ${{ secrets.AWS_USE_PATH_STYLE_ENDPOINT }}
          VITE_APP_NAME: ${{ secrets.VITE_APP_NAME }}
        run: |
          docker build --build-arg APP_NAME="$APP_NAME" \
            --build-arg APP_ENV="$APP_ENV" \
            --build-arg APP_KEY="$APP_KEY" \
            --build-arg APP_DEBUG="$APP_DEBUG" \
            --build-arg APP_URL="$APP_URL" \
            --build-arg LOG_CHANNEL="$LOG_CHANNEL" \
            --build-arg LOG_DEPRECATIONS_CHANNEL="$LOG_DEPRECATIONS_CHANNEL" \
            --build-arg LOG_LEVEL="$LOG_LEVEL" \
            --build-arg DB_CONNECTION="$DB_CONNECTION" \
            --build-arg DB_HOST="$DB_HOST" \
            --build-arg DB_PORT="$DB_PORT" \
            --build-arg DB_DATABASE="$DB_DATABASE" \
            --build-arg DB_USERNAME="$DB_USERNAME" \
            --build-arg DB_PASSWORD="$DB_PASSWORD" \
            --build-arg SESSION_DRIVER="$SESSION_DRIVER" \
            --build-arg SESSION_LIFETIME="$SESSION_LIFETIME" \
            --build-arg REDIS_CLIENT="$REDIS_CLIENT" \
            --build-arg REDIS_HOST="$REDIS_HOST" \
            --build-arg REDIS_PASSWORD="$REDIS_PASSWORD" \
            --build-arg REDIS_PORT="$REDIS_PORT" \
            --build-arg MAIL_MAILER="$MAIL_MAILER" \
            --build-arg MAIL_SCHEME="$MAIL_SCHEME" \
            --build-arg MAIL_HOST="$MAIL_HOST" \
            --build-arg MAIL_PORT="$MAIL_PORT" \
            --build-arg MAIL_USERNAME="$MAIL_USERNAME" \
            --build-arg MAIL_PASSWORD="$MAIL_PASSWORD" \
            --build-arg MAIL_FROM_ADDRESS="$MAIL_FROM_ADDRESS" \
            --build-arg MAIL_FROM_NAME="$MAIL_FROM_NAME" \
            --build-arg AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
            --build-arg AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
            --build-arg AWS_DEFAULT_REGION="$AWS_DEFAULT_REGION" \
            --build-arg AWS_BUCKET="$AWS_BUCKET" \
            --build-arg AWS_ENDPOINT="$AWS_ENDPOINT" \
            --build-arg AWS_URL="$AWS_URL" \
            --build-arg AWS_USE_PATH_STYLE_ENDPOINT="$AWS_USE_PATH_STYLE_ENDPOINT" \
            --build-arg VITE_APP_NAME="$VITE_APP_NAME" \
            -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
